x1=float(input("enter the x-cordinate of 1st point :- "))
y1=float(input("enter the y-cordinate of 1st point :- "))
x2=float(input("enter the x-cordinate of 2nd point:- "))
y2=float(input("enter the y-cordinate of 2nd point :- "))
slope=abs((y2-y1)/(x2-x1))
print("the slope of line between two point is",slope)